# This is a config for E2B sandbox template.
# You can use template ID (8nr2r2rr46jiqbarg5px) or template name (vibe-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-2')

team_id = "d586c8c1-45eb-42fa-a4c2-e5a71a619c2b"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-2"
template_id = "8nr2r2rr46jiqbarg5px"
